-- AlterTable
ALTER TABLE "ikli_scores" ADD COLUMN     "acv" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "gap" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "harapan_raw" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "ihli" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "pcgv" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "skor_harapan" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "skor_kepuasan" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "udcv" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE "survey_answers" ADD COLUMN     "expectation_value" INTEGER;

-- AlterTable
ALTER TABLE "survey_indicators" ADD COLUMN     "aspek" TEXT,
ADD COLUMN     "dimensi" TEXT,
ADD COLUMN     "unsur" TEXT;
